name: Deploy UI
run-name: Deploy UI (${{github.event_name == 'workflow_dispatch' && 'local' || github.event.client_payload.environment}}) (${{github.event_name == 'workflow_dispatch' && github.event.inputs.app-build-number || github.event.client_payload.ref}})

on:
  repository_dispatch:
    types:
      - deploy-ui

  workflow_dispatch:
    inputs:
      sabaq-ref:
        description: "Sabaq repo ref (branch, tag, etc.)"
        required: true
        default: "master"
      app-build-number:
        description: "App build number (e.g., 100)"
        required: true
      development-server-host:
        description: "Development server host (e.g., localhost, staging.example.com)"
        required: false

env:
  SABAQ_ENV: ${{github.event_name == 'workflow_dispatch' && 'local' || github.event.client_payload.environment}}
  SABAQ_REF: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.sabaq-ref || github.event.client_payload.ref}}

jobs:
  deploy-ui:
    strategy:
      matrix:
        platform: ${{github.event_name == 'workflow_dispatch' && fromJson('["ios", "android"]') || fromJson('["ios", "android", "web"]')}}

    runs-on: ${{ matrix.platform == 'ios' && 'macos-26' || 'ubuntu-24.04' }}

    env:
      MOBILE_BUILD_PATH: /tmp/sabaq.${{matrix.platform == 'ios' && 'ipa' || (github.event_name == 'workflow_dispatch' && 'apk' || 'aab')}}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: cjiis/sabaq
          token: ${{secrets.GH_PAT}}
          ref: ${{env.SABAQ_REF}}

      - if: ${{matrix.platform == 'ios'}}
        uses: ./.github/actions/setup-xcode
      - if: ${{matrix.platform == 'android'}}
        uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-node

      - run: npm ci

      - if: ${{matrix.platform == 'web'}}
        run: npm run expo export -- --platform web
        env:
          EXPO_PUBLIC_DO_NOT_USE_FIREBASE_EMULATORS: "true"
          EXPO_PUBLIC_TRPC_ENDPOINT: ${{env.SABAQ_ENV == 'prod' && 'https://apiv2-3yoyqfllna-uc.a.run.app/trpc' || 'https://apiv2-drlhhmghsa-uc.a.run.app/trpc'}}
          EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{env.SABAQ_ENV == 'prod' && 'pk_live_51QBmL3Bi17HmM2BuKrxBF90aW2AjrN7fVukBRKpH5P7tEJUDjtUaj8kL3zWEXn2lnPnKbu5z8zAn1f5UmG4VJpWf00Gbz2quPA' || 'pk_test_51QBmL3Bi17HmM2BuzGCSGA4KVJxhqt8y9dPTij7tEauokrE4GA88cxpYIP65CwxlljIhqW8fm4Drq7Y3JYIGNML100njJBTv0z'}}
          EXPO_PUBLIC_SABAQ_ENV: ${{env.SABAQ_ENV}}
      - if: ${{matrix.platform == 'web'}}
        run: npm run firebase -- deploy --only hosting:app --project ${{env.SABAQ_ENV}} --token ${{secrets.FIREBASE_TOKEN}}

      - if: ${{matrix.platform == 'ios' || matrix.platform == 'android'}}
        run: npm run build -- --non-interactive --output ${{env.MOBILE_BUILD_PATH}} --platform ${{matrix.platform}} --profile ${{env.SABAQ_ENV}}
        env:
          EXPO_TOKEN: ${{secrets.EXPO_TOKEN}}
          EXPO_PUBLIC_FIREBASE_EMULATORS_HOST: ${{github.event.inputs.development-server-host}}
      - if: ${{matrix.platform == 'ios' || matrix.platform == 'android'}}
        run: npm run eas -- submit --non-interactive --path ${{env.MOBILE_BUILD_PATH}} --platform ${{matrix.platform}} --profile ${{env.SABAQ_ENV}}
        env:
          EXPO_TOKEN: ${{secrets.EXPO_TOKEN}}
