run-name: Deploy UI (${{ github.event_name == 'workflow_dispatch' && 'local' || github.event.client_payload.environment }}) (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.app-version || github.event.client_payload.ref }})
on:
  repository_dispatch:
    types:
      - deploy-ui
  workflow_dispatch:
    inputs:
      app-version:
        description: "App version to deploy (e.g., 1.0.0)"
        required: true
      app-build-number:
        description: "App build number (e.g., 100)"
        required: true
jobs:
  deploy-ui:
    strategy:
      matrix:
        platform:
          - ios
          - android
          - web
    runs-on: ${{ matrix.platform == 'ios' && 'macos-26' || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: cjiis/sabaq
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.client_payload.ref }}
      - uses: ./.github/actions/setup-xcode
        if: ${{ matrix.platform == 'ios' }}
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/scripts
        env:
          action: deploy-ui
          platform: ${{ matrix.platform }}
          expoToken: ${{ (matrix.platform == 'ios' || matrix.platform == 'android') && secrets.EXPO_TOKEN }}
          firebaseToken: ${{ matrix.platform == 'web' && secrets.FIREBASE_TOKEN }}
          environment: ${{ github.event_name == 'workflow_dispatch' && 'local' || github.event.client_payload.environment }}
          appVersion: ${{ github.event.inputs.app-version }}
          appBuildNumber: ${{ github.event.inputs.app-build-number }}
