on:
  repository_dispatch:
    types:
      - deploy-ui
jobs:
  deploy-ui:
    strategy:
      matrix:
        platform:
          - ios
          - android
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
        with:
          repository: cjiis/sabaq
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.client_payload.ref }}
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-eas
      - uses: ./.github/actions/setup-fastlane
      - uses: ./.github/actions/setup-firebase
      - uses: ./.github/actions/scripts
        env:
          action: deploy-ui
          platform: ${{ matrix.platform }}
          expoToken: ${{ secrets.EXPO_TOKEN }}
          firebaseToken: ${{ secrets.FIREBASE_TOKEN }}
