on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: gem install fastlane
      - run: fastlane --version
  mac-test:
    runs-on: macos-latest
    steps:
      - run: gem install fastlane
      - run: fastlane --version
